services:
  # app:
  #   container_name: hookylog-app
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   depends_on:
  #     - postgres
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - hookylog
  #   env_file:
  #     - .env
  postgres:
    container_name: hookylog-postgres
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    networks:
      - hookylog
    environment:
      - POSTGRES_DB=hookylog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

networks:
  hookylog:
    driver: bridge
